### ISSUE TITLE
Fixing Melpa Recipe

### ISSUE THREAD

**Issue by gopar** [emacs-eclim/emacs-eclim#1]
So just like @kleewho said, I think we should figure out how to fix the whole [recipe](https://github.com/milkypostman/melpa/blob/b9faeb6d910d686cbcafe7d12e0bcf62a85689bd/recipes/emacs-eclim) thing from melpa since it points to the original. But I also think we should first commit some code to show that we're actually committed to this thing.

Any opinions?

**Comment by nloyola** [comment]
I just merged a few of my changes and another one by @ovy (ovy/emacs-eclim@833734653aa1316f247278a13aa7db6036f323c7).

**Comment by gopar** [comment]
@nloyola are you reviewing the source code before merging? I know that we need to show some commits but not at the expense of creating an unstable package. I'm not saying that the merges contain bad code but that they should be reviewed over. I see you've done quite a few merges already.

**Comment by nloyola** [comment]
Yes, I reviewed the changes I merged into master and have been using them via my fork for over a month.

**Comment by nloyola** [comment]
I've submitted a pull request on the Melpa respository: milkypostman/melpa#3400.

**Comment by nloyola** [comment]
This repository is now live on Melpa: https://melpa.org/#/emacs-eclim.
