### ISSUE TITLE
No completion after dot

### ISSUE THREAD

**Issue by joostkremers** [emacs-eclim/emacs-eclim#10]
I'm using company as my completion library and I have `company-emacs-eclim` installed. When editing a Java file, completion works, but only to a certain extent. If I type, e.g., `Sys`, I get a bunch of completion candidates, one of which is `System`. After selecting this option and typing `.` (i.e., a dot), I would expect completion to start again, showing me the possible functions / packages under `System`. Instead, nothing happens. I have to type three characters to activate completion again. Doing `M-x company-complete` after the dot doesn't do anything either.

The thing is, it works fine in Python files. With an `import math` in the file, typing `math.` gives me a list of functions in the `math` package. So it's not the dot per se that is problematic for company, it seems.

Am I missing something in my configuration? (I looked at the Customize group for `company-eclim`, but there was only one option that is not relevant.) If not, where should I start looking in order to debug this?

Emacs: 25.1.1
eclim (Emacs package): 20160901.16
eclim/eclimd: 2.5.0
eclipse: 4.5.0
jdk: 1.8.0

**Comment by nloyola** [comment]
When I type `System.`, I have to then invoke `company-complete-common` (which I have bound to <kbd>M-/</kbd>) to see the candidates. 

I found this page: http://tkf.github.io/emacs-jedi/latest/. It states that `jedi:complete-on-dot` has to be enabled for completion to be invoked.

I not sure if completion on dot is enabled by Eclim.

**Comment by joostkremers** [comment]
> When I type `System.`, I have to then invoke `company-complete-common` (which I have bound to `M-/`) to see the candidates.

Yes, that works for me, too.

> I found this page: http://tkf.github.io/emacs-jedi/latest/. It states that jedi:complete-on-dot has to be enabled for completion to be invoked.

Well, that page is for Python completion with jedi, which is an extension for the `auto-complete` package. I don't use `auto-complete`, I use `company`. So I don't think that page is relevant to my issue, unfortunately.

**Comment by nloyola** [comment]
I don't think this issue is a bug in Eclim. It deals with the way you want company to work for you and therefore related to company configuration.

**Comment by joostkremers** [comment]
I just looked into it a bit more and it _is_ a bug in emacs-eclim, I think. If you replace the following snippet in `company-emacs-eclim`:

``` emacs-lisp
(prefix (let ((start (and eclim-mode
                          (eclim--accepted-p (buffer-file-name))
                          (eclim-completion-start))))
          (when start (buffer-substring-no-properties start (point)))))
```

with this:

``` emacs-lisp
(prefix (company-grab-symbol-cons "\\."))
```

it works. Crucially, the original code uses `eclim-completion-start`, which in turn uses `(beginning-of-thing 'symbol)` to find the beginning of the thing to complete. Right after a dot, however, that call produces an error, which `eclim-completion-start` ignores, resulting in an empty `prefix` an no completion.

Now, there's probably a reason why `company-emacs-eclim` uses some custom code to calculate the prefix rather than `company-grab-symbol-cons` (though TBH I don't understand why it's necessary to check `eclim-mode` and `eclim--accepted-p` each time a completion prefix is calculated), so I'm not saying that using `company-grab-symbol-cons` is the right solution. Presumably, `eclim-completion-start` should be patched to allow for the dot.

**Comment by joostkremers** [comment]
Well, I tried the obvious change:

```
eclim-completion.el | 3 ++-

modified   eclim-completion.el
@@ -190,7 +190,8 @@ buffer."
                          ;; no particular harm done.
                          (and (eq ?\< (char-before))
                               (memq major-mode
-                                    '(java-mode c++-mode groovy-mode))))
+                                    '(java-mode c++-mode groovy-mode)))
+                         (eq ?\. (char-before)))
                  (backward-char 1))
                (ignore-errors (beginning-of-thing 'symbol))
                ;; Completion candidates for annotations don't include '@'.
```

(BTW, that was after I fixed a typo: `groovy-mode` is actually `goovy-mode` in the actual code.)

This now gives me completion when I type `System.`, but the dot still does not count for `company-minimum-prefix-length`, so when I type `System.out.pr`, there is no completion (with the default value for `company-minimum-prefix-length` of 3).

If I use `(company-grab-symbol-cons "\\.")`, there _is_ completion after `System.out.pr`, which is presumably the result of `company-grab-symbol-cons` returning `("pr" . t)` in that case. (I'm not familiar with the inner workings of `company` but it seems obvious that the cons is used to signal that completion should actually involve more than just the returned string.)

**Comment by joostkremers** [comment]
> (though TBH I don't understand why it's necessary to check `eclim-mode` and `eclim--accepted-p` each time a completion prefix is calculated),

Some testing revealed that it _is_ necessary. Like I said, I'm not familiar with the inner workings of `company-mode`...

**Comment by nloyola** [comment]
Closing for now. Can be reopened if more information is provided.
