### ISSUE TITLE
Company completion error when completing import type

### ISSUE THREAD

**Issue by timcharper** [emacs-eclim/emacs-eclim#15]
When I use company-mode completion on a type that isn't imported, I get the following error message:

```
Company: backend company-emacs-eclim error "Symbol’s function definition is void: eclim/execute-command" with args (post-completion Array - javaslang.collection)
```

**Comment by timcharper** [comment]
It turns out that loading eclim with `(require 'eclim)` wasn't enough. I had to manually `(require 'eclim-macros)`. It looks like the macro [is only loaded when compiling](https://github.com/emacs-eclim/emacs-eclim/blob/f2247f2515ee2eb0ff866bcbbf69d9f62b7b7780/eclim.el#L38)... although I installed this from melpa. Not sure why this isn't working.

**Comment by nloyola** [comment]
What version of Emacs are you using? I do not get this error and I'm using Emacs 25.1.1 on Ubuntu.

**Comment by timcharper** [comment]
Same version of emacs here but OS X. Maybe my loading approach is wrong. How do you activate eclim?

**Comment by nloyola** [comment]
I'm using [use-package](https://github.com/jwiegley/use-package) to load Eclim.

``` emacs-lisp
(use-package company-emacs-eclim
  :ensure t
  :commands company-emacs-eclim-setup)
(use-package eclimd
  :commands start-eclimd)
(use-package eclim
  :diminish eclim-mode
  :commands (global-eclim-mode)
  :init (use-package cl)
  :config
  ...)
```

How do you load it?

**Comment by nloyola** [comment]
Closing this since there has been no feedback. Issue can be re-opened at a later time.
