### ISSUE TITLE
Improve Usage Guide

### ISSUE THREAD

**Issue by luisgerhorst** [emacs-eclim/emacs-eclim#17]
Hi,
I just set up emacs-eclim for the first time. The install guide worked very good, I just had problems getting it to actually _work_ since as a new user I had no idea that I need to creat a .project file and whether the server got already started or if I have to do it manually. Adding those 2 to the Usage guide would ge a great Addition I think. Maybe also mention that the eclim Usage guide is also relevant for emacs-eclim and link it somewhere? (I first thought it was only for vim users.)

**Comment by nloyola** [comment]
Thanks for your comments. I assume by *Usage guide* you mean the [README.md](https://github.com/emacs-eclim/emacs-eclim/blob/master/README.md) file. 

Would you be willing to submit a pull request for the additions you suggest?

**Comment by luisgerhorst** [comment]
Yeah sure I can do that, just give me some time :)
