### ISSUE TITLE
Error starting eclim-mode, likely caused by new eclimd-autostart changes.

### ISSUE THREAD

**Issue by pheaver** [emacs-eclim/emacs-eclim#31]
As of 1cd950ef1db673ca0e82b5607f2da744ebbcf73c, I get this error whenever I enable eclim-mode:

```eclimd--ensure-started: Symbol's value as variable is void: caller-current-buffer```

The problem is somewhere in ```eclim--lambda-with-live-current-buffer```.

I have verified that the previous commit (1fea103f4f209ee89d6690ca30a417a566d1928a) works fine.

```emacs-version``` is ```24.5.1```. I will try on emcas 25 as well.

**Comment by pheaver** [comment]
Same problem on emacs 25.

The problem in ```eclim--lambda-with-live-current-buffer``` has something to do with the ```caller-current-buffer``` symbol not being in scope in the lambda that the macro returns.

**Comment by nloyola** [comment]
@luisgerhorst would you have any time to look into this?

**Comment by luisgerhorst** [comment]
Sure, thanks for the report. @pheaver I'll look into it shortly, can you send a stack trace ("M-: (setq debug-on-error t)" before enabling eclim-mode) in the meantime?

**Comment by pheaver** [comment]
Here's the stack trace when I run eclim-mode manually:

```Debugger entered--Lisp error: (void-variable caller-current-buffer)
  #[nil "\301!\205
�rq\210\302 )\207" [caller-current-buffer buffer-live-p eclim--maybe-create-project] 2]()
  eclimd--ensure-started(t #[nil "\301!\205
�rq\210\302 )\207" [caller-current-buffer buffer-live-p eclim--maybe-create-project] 2])
  eclim-mode(toggle)
  call-interactively(eclim-mode record nil)
  command-execute(eclim-mode record)
  helm-M-x(nil #("eclim-mode" 0 10 (match-part "eclim-mode")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by luisgerhorst** [comment]
Thanks!

**Comment by luisgerhorst** [comment]
Hmm I wasn't able to reproduce it yet. Can you send the config you are using? Can you try [this minimal config](https://gist.github.com/luisgerhorst/b8473dbcbfa731d1f56e1b60bf8ffd17), if it still doesn't work with the minimal config:

- How did you install emacs-eclim?
- Seems as if the source files are compiled, can you send a stack trace that uses the raw source files? Edit: As much as I can read from the byte code `caller-current-buffer` is not referenced as a lexical variable (which it should be), if I disable lexical binding in `eclim.el` and compile the file I can reproduce the error.

If it works with the minimal config, sending as much of you .emacs.d as possible is enough.

**Comment by luisgerhorst** [comment]
I just saw that the file that contains `eclim--lambda-with-live-current-buffer` did not yet have lexical binding enabled in 1cd950e, so just to be sure do test with the latest commit (since you said as of 1cd950e, I guess you alread did that).

**Comment by luisgerhorst** [comment]
Some crazy idea you can check: Some systems have older versions of Emacs installed which may shadow the version you are actually using when you byte compiled the files. If the version that compiles the files does not support lexical binding it would produce the byte code you posted.

**Comment by pheaver** [comment]
I am using emacs 24 and am certain that emacs-eclim was built from it. Isn't lexical scoping off by default in emacs24 and it needs to be enabled per buffer?

**Comment by luisgerhorst** [comment]
Yes exactly, you can check whether eclim.el contains "lexical-binding: t" in the first line to be sure.

**Comment by pheaver** [comment]
I installed eclim from elpa: eclim-20170101.1334. There was no lexical-binding line at the top of the file.

I upgraded to eclim-20170107.2050, and lexical-binding is there now.

There was a commit 6a2893d "Remove lexical binding for now" on master. I bet that was it.

**Comment by pheaver** [comment]
I'm pretty sure that fixed the problem. I just can't tell, because it created a new problem:

```eclim--expand-args: Assertion failed: (or (stringp (cadr arg)) (numberp (cadr arg)))```

I'll look into that and maybe submit a separate issue.

**Comment by luisgerhorst** [comment]
Ah sorry. Yes I remember, that was a mistake.

**Comment by luisgerhorst** [comment]
Ok thanks! Thats interesting the assertion were just added.

**Comment by pheaver** [comment]
Somewhat off topic now, but I found that ```eclim--expand-args``` is being passed ```(("-f" 'file))```, where ```file``` is a symbol and not a string, which is why the assertion fails.

**Comment by pheaver** [comment]
Hacked my way past that error and now it just says ```eclim--lambda-with-live-current-buffer``` isn't defined (it's a macro supposed to be loaded at compile time)...

**Comment by pheaver** [comment]
eclim-0.3 (from melpa stable) also doesn't work:

```error in process sentinel: Symbol's value as variable is void: on-complete-fn```

So I'm having trouble getting any version of eclim to work right now...

**Comment by luisgerhorst** [comment]
Hmm, have you tried installing it via git?

**Comment by pheaver** [comment]
Yes, see https://github.com/emacs-eclim/emacs-eclim/issues/33.

**Comment by nloyola** [comment]
@pheaver Once we fix the issue you are having, we will release a new version to Melpa stable.

**Comment by nloyola** [comment]
@pheaver Melpa is now updated to provide 20170107.2050 of the eclim package. Can you please update your Melpa package and see if you still have the problem?

Also, please make sure you are not using the package from the cloned repository.

**Comment by pheaver** [comment]
@nloyola Confirmed. Installed eclim 20170107.2050 from melpa. Works perfectly. Was not using the cloned repo.

**Comment by nloyola** [comment]
@pheaver is OK to close this issue now since you don't see the error anymore?

**Comment by nloyola** [comment]
@pheaver I just created the 0.4 tag on this repository. The new version should be available on Melpa Stable shortly.

**Comment by pheaver** [comment]
Awesome!
