### ISSUE TITLE
Use Flycheck for problems display?

### ISSUE THREAD

**Issue by luisgerhorst** [emacs-eclim/emacs-eclim#35]
I recently encountered a problem when using emacs-eclim together with Flycheck. Specificly the suggested config for displaying compilation error messages at point (which includes setting `help-at-pt-timer-delay`) overrides Flycheck's `flycheck-display-errors-delay` globally. I also don't think there's a way to make the config local to emacs-eclim buffers.

Why not remove the custom code and directly use Flyckeck to display the problems? Is there anything special about the way emacs-eclim displays errors? If you think it's a good idea I can try doing this.

**Comment by nloyola** [comment]
I'm not sure about this, but I am led to believe that Emacs Eclim was written before Flycheck became popular. So, the problem you are pointing out may not have been a consideration at the time. Please have a look and see if you can make it work better.

I think the errors come directly from the `eclimd` process, so I'm not sure how that would integrate well with Flycheck. Would the errors reported by both be merged in some way? And, duplicates removed?

**Comment by luisgerhorst** [comment]
I haven't really looked into it but I think Flycheck by default does not provide a checker for Java so there should not be a problem with duplicate errors. I'll try it out and see if its a good option.
