### ISSUE TITLE
Does not generate constructor properly

### ISSUE THREAD

**Issue by tkamat** [emacs-eclim/emacs-eclim#38]
In vim eclim allows you to generate constructors for fields by selecting them, and then running JavaConstructor. Sadly this does not work with emacs-eclim, and it only generates an empty constructor, which isn't of much use. It would be great if you guys would implement this feature, as it is the main thing preventing me from making the switch from intelliJ!

**Comment by nloyola** [comment]
Can you provide more details please? I'm not a Vim user and it would take me some time to try and set up a project under Vim.

Thanks

**Comment by tkamat** [comment]
Basically with eclim for vim you could select a group of instance variables, and jun the command to create a constructor. Instead of creating an empty constructor, it would create a constructor initializing all of the variables selected.

**Comment by nloyola** [comment]
How do you select the instance variables with Vim? Would it be the same as using the *region* in Emacs?

Does the **Constructors** section on this [page](http://eclim.org/vim/java/methods.html) describe it?

**Comment by tkamat** [comment]
Yes, just like that.

**Comment by nloyola** [comment]
Would you be willing to submit a pull request for this?

**Comment by tkamat** [comment]
I do not have much experience with projects like this, so most likely no.

**Comment by nloyola** [comment]
Fixed with pull request #51.
