### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by kwvanderlinde** [emacs-eclim/emacs-eclim#47]
Many of the elements (functions, variables, etc.) of this package are undocumented.

For the most part, I think public elements are documented, so it's not a big deal for end users. But it would be ideal if the internal parts were also documented, to make it easier to hack on the package.

**Comment by nloyola** [comment]
Please submit pull requests for this. I would gladly merge them.

The people that originally wrote the code no longer contribute to this project.

**Comment by kwvanderlinde** [comment]
@nloyola Of course. I'm working on adding documentation and fixing up existing documentation where I can.

**Comment by nloyola** [comment]
Closing for now. Can be reopened at a later date.
