### ISSUE TITLE
Compilation warnings when installing package.

### ISSUE THREAD

**Issue by kwvanderlinde** [emacs-eclim/emacs-eclim#54]
## Expected behavior

No errors or warnings should be produced when installing any eclim packages.

## Actual behavior

The following warnings are produced when installing the `eclim` package (I have removed the lines for files which do not produce warnings):

```
Compiling file /home/ken/.emacs.d/elpa/eclim-20170328.1807/eclim-common.el at Fri Mar 31 15:12:45 2017

In eclim-java-archive-file:
eclim-common.el:558:33:Warning: `"-f"' is a malformed function

In end of data:
eclim-common.el:949:1:Warning: the function
    `eclim--get-problems-buffer-create' is not known to be defined.

...

Compiling file /home/ken/.emacs.d/elpa/eclim-20170328.1807/eclim-java.el at Fri Mar 31 15:12:45 2017
eclim-java.el:469:1:Warning: Unused lexical argument `noconfirm'
eclim-java.el:469:1:Warning: Unused lexical argument `ignore-auto'

In end of data:
eclim-java.el:878:1:Warning: the function
    `eclim--current-region-no-properties' is not known to be defined.

...

eclim-project.el:155:1:Warning: Unused lexical argument `depends'
```

The other eclim packages `company-emacs-eclim` and `ac-emacs-eclim` do not report any warnings or errors.

## Steps to reproduce the problem

- `M-x package-list-packages`
- Mark `eclim` for installations.
- `M-x package-menu-execute`

### package version information

MELPA 20170328.1807

### Java Development Kit Version

JDK 1.8

### Eclipse version

Eclipse 4.6.2 (Neon)

### Eclim version

2.6.0

### Emacs version

24.5.1

### Operating system

Ubuntu 16.04

**Comment by kwvanderlinde** [comment]
I should note that these seem to be the exact same warnings generated by cask when running `make compile`.

**Comment by nloyola** [comment]
See also commits 1f9addf8 and 90547a1a.
