### ISSUE TITLE
Imports not added in top of file.

### ISSUE THREAD

**Issue by kwvanderlinde** [emacs-eclim/emacs-eclim#55]
## Expected behavior

Imports added by `eclim-java-import-organize` are added at the top of a Java file outside any classes.

## Actual behavior

If there is no lines before the class at the top of the file (including no blank lines), the imports are added inside the class. Otherwise, it seems to work correctly as long as a single line, even a blank line, is first inserted before the class.

## Steps to reproduce the problem

Start with an Eclipse project containing the following file, called `Test.java` (the names here aren't important):

```
public class Test {
	public void someMethod() {
		Paths.get("Hello");
	}
}
```

Note that there are no lines before class `Test`. Also note that there is no line `import java.nio.file.Paths;`.

Now run `eclim-java-import-organize` (which for me is bound to `C-c C-e i`), and we get

```
public class Test {

import java.nio.file.Paths;

	public void someMethod() {
		Paths.get("Hello");
	}
}
```

Although the import statement is correct, it is inside the class which is illegal.

### package version information

MELPA 20170328.1807

### Java Development Kit Version

JDK 1.8

### Eclipse version

Eclipse 4.6.2 (Neon)

### Eclim version

2.6.0

### Emacs version

24.5.1

### Operating system

Ubuntu 16.04

**Comment by afeicool** [comment]
same issue

**Comment by tkamat** [comment]
Yeah for me they always end up in the javadoc comment above the class.
