### ISSUE TITLE
eclim freezes by auto-save-file

### ISSUE THREAD

**Issue by nloyola** [emacs-eclim/emacs-eclim#56]
emacs-eclim freezes when emacs generates auto-save-file, such as `#Main.java#`.
`(setq auto-save-default nil)` solved it.

Originally submited as senny/emacs-eclim#276.

**Comment by nloyola** [comment]
Cannot reproduce this issue on Emacs 25.2.1 and Ubuntu 17.04.

**Comment by stardiviner** [comment]
Does this because `eclim` always save buffer for completion? Why not don't save buffer to file, just complete directly?

**Comment by nloyola** [comment]
@stardiviner what do you mean by:

> Why not don't save buffer to file, just complete directly?

I'm having trouble understanding your question.

In most scenarios, a file must be saved to disk before a call to the Eclim server is made. The Eclim server then makes the appropriate changes to the file and then the Emacs Eclim package reloads the file.

**Comment by stardiviner** [comment]
I found `company-emacs-eclim` will save buffer everytime I type a character to get completion.
This is annoying.

> In most scenarios, a file must be saved to disk before a call to the Eclim server is made. The Eclim
> server then makes the appropriate changes to the file and then the Emacs Eclim package reloads the
> file.

There is no way to change this communication by using current buffer content? (I guess many other packages like [robe](https://github.com/dgutov/robe) use this way.)

**Comment by nloyola** [comment]
@stardiviner that is the way Eclim works on Vim and Emacs. Sorry.

**Comment by stardiviner** [comment]
@nloyola I see, thanks for your answering.

**Comment by nloyola** [comment]
Closing this due to no replies from those that reported the issue: @squarepegsys, @tsukimizake, @sandric, and @jchaffin. 

Will re-open if issue persists.
