### ISSUE TITLE
:JavaNew?

### ISSUE THREAD

**Issue by onizucraft** [emacs-eclim/emacs-eclim#57]
Hi there. First of all, thank you for porting eclim to emacs ;)

I've been searching for the new type function (vim's :JavaNew) and didn't found it. Are you planning to include it? Is there a way to use it?

Cheers.

**Comment by nloyola** [comment]
I haven't had much time to devote to this project lately. If you'd like to submit a pull request it will always be welcome.

**Comment by nloyola** [comment]
From the command line, the command is:

```sh
eclim -command java_new -p PROJ_NAME -t class -n PACKAGE.CLASS_NAME -r PROJECT_PATH
```

See [here](http://eclim.org/vim/java/types.html) for documentation.

If I have enough time, I will work on this shortly.

**Comment by onizucraft** [comment]
I will try to invest some time on it, although I have 0 experience with
lisp :D

**Comment by nloyola** [comment]
@gabrielps I committed a change for this. Please try it out when Melpa gets updated to this version.

**Comment by nloyola** [comment]
Closing for now. Will re-open if any issues are reported.
