### ISSUE TITLE
How to connect to external eclimd process?

### ISSUE THREAD

**Issue by stardiviner** [emacs-eclim/emacs-eclim#58]
If I start eclimd external process in shell with command: `/usr/lib/eclipse/plugins/org.eclim_2.6.0/bin/eclimd -Dosgi.instance.area.default=/home/stardiviner/Code/Java`.
How can I connect to external eclimd process in Emacs?

**Comment by nloyola** [comment]
If you've configured your `java-mode-hook`, just open up a `Java` file in Emacs and it will detect the running instance of the Eclimd server. If that does not work type <kbd>M-x global-eclim-mode</kbd>.

If you want to configure it correctly you should add this to your config:

```emacs-lisp
(add-hook 'java-mode-hook (lambda() (eclim-mode t))) 
```

Also, see the **Starting eclimd** section in [README.md](https://github.com/emacs-eclim/emacs-eclim/blob/master/README.md).

**Comment by stardiviner** [comment]
I found there is a problem, Eclim can auto detect the external eclimd process, and works fine. But problem is that when I quit Emacs, eclim will close the external eclimd process too. I hope Eclim can improve on this  don't close external eclimd process, only close Emacs internal eclimd process.

**Comment by nloyola** [comment]
I don't have this problem. In the the **Starting eclimd** section in [README.md](https://github.com/emacs-eclim/emacs-eclim/blob/master/README.md) it states that you have to set `eclimd-autostart` to `nil`. Have you done that?

**Comment by stardiviner** [comment]
Yes, I have setted that.

**Comment by stardiviner** [comment]
```elisp
(use-package eclim
  :ensure t
  :defer t
  :init
  ;; Control `eclimd' from emacs
  (require 'eclimd)

  (setq eclimd-autostart nil
        eclimd-autostart-with-default-workspace t
        eclimd-default-workspace "~/Code/Java"
        eclimd-wait-for-process nil)
  
  ;; auto enable `eclim-mode' in `java-mode'.
  (add-hook 'java-mode-hook 'eclim-mode)
  ;; (global-eclim-mode t)
  :config
  ;; Eclim Java
  ;; (setq eclim-java-documentation-root nil
  ;;       eclim-java-android-documentation-root
  ;;       )
  )
```

**Comment by nloyola** [comment]
I still cannot reproduce your problem. I have copied your config to mine. Can you add `(setq eclim-print-debug-messages t)` to your config, reproduce your problem, and then send me what gets output to your `*Messages*` buffer?

**Comment by nloyola** [comment]
Also, do you start the `eclimd` executable and Emacs in different shells? If not, can you try that?

**Comment by stardiviner** [comment]
I start `eclimd` with command: `/usr/lib/eclipse/plugins/org.eclim_2.6.0/bin/eclimd -Dosgi.instance.area.default=/home/stardiviner/Code/Java`. And in tmux two different panes. This should be two different shells.

**Comment by stardiviner** [comment]
After test, this problem does not exist, maybe because the last time I enable `global-eclim-mode` or something else, triggered `(add-hook 'kill-emacs-hook #'stop-eclimd)` in `start-eclimd`.
Sorry for the distribution.
