### ISSUE TITLE
Use existing eclimd instances

### ISSUE THREAD

**Issue by kminh** [emacs-eclim/emacs-eclim#60]
Hi, thank you very much for this mode.

Currently I have two eclimd instances started manually outside of emacs and would like to know if there's a way to use them instead of starting one from within emacs. Each of my eclimd instance has a workspace of its own FYI.

Thank you in advance for any insights.

**Comment by nloyola** [comment]
I can confirm that it works when one is started from the command line or from Eclipse.

I'm not sure how to make it work with two different instances of the server.

**Comment by kminh** [comment]
How should I configure to make it work with one instance? Should I point the eclimd executable to the one I'm using (a custom one) and then use `start-eclimd` and it will auto-detect the existing process?

Thank you.

**Comment by nloyola** [comment]
The process is detected automatically as soon as `eclim-mode` or `global-eclim-mode` is enabled.

You can configure as follows:

```emacs-lisp
(require 'eclim)
(setq eclimd-autostart nil)
(global-eclim-mode)
```

Or:

```emacs-lisp
(require 'eclim)
(setq eclimd-autostart nil)

(defun my-java-mode-hook ()
    (eclim-mode t))

(add-hook 'java-mode-hook 'my-java-mode-hook)
```

**Comment by kminh** [comment]
I've already put those lines into my dot emacs file. Keep getting this message:

![screenshot from 2017-05-18 23-09-32](https://cloud.githubusercontent.com/assets/6402124/26212410/ab10682e-3c1f-11e7-9c93-4ba104a8e32b.png)

After that when I try to complete anything I just receive connection refused error.

Do I need to set the default workspace to the same one being used by the process as well? Any other parameter that needs to match such as the port?

**Comment by nloyola** [comment]
How are you starting your Eclimd Server? If you are getting connection refused, it means that the Emacs Eclim package is not connecting to your Eclimd Server.

**Comment by kminh** [comment]
I'm starting my eclimd server as a systemd service using this command:
```
/path/to/eclipse/eclimd -f ~/.eclim/eclimrc
```
This is the contents of my `eclimrc`:
```
osgi.instance.area.default=/path/to/my/workspace
nailgun.server.port=9092
```
Just a side note, I can ping the eclimd server just fine from Vim.

**Comment by nloyola** [comment]
The default port is 9091. How do you get 9092?

I don't think the current implementation of Emacs Eclim looks at `~/.eclim/eclimrc`.

**Comment by kminh** [comment]
That is my second instance of eclimd so I'm using 9092. So I should make sure that the workspace and the port match, or matching only the port is enough?

**Comment by nloyola** [comment]
Looking at the usage for the Eclim executable gives this:

```sh
> ./eclim -\?         

Usage: eclim [-f eclimrc] [--nailgun-port port] -command command [args]
```

It supports the `-f` and `--nailgun-port` parameters. I don't think usage of these paraemters has been implemented in the Emacs Eclim package yet.

I will open a new issue for this.

Sorry, but for now only a single Eclimd Server instance, running on port 9091, is supported.
