### ISSUE TITLE
Allow Emacs Eclim to use -f and --nailgun-port parameters

### ISSUE THREAD

**Issue by nloyola** [emacs-eclim/emacs-eclim#61]
The Eclim executable allows the `-f` parameter to specify an `eclimrc` file. Also, the `--nailgun-port` parameter can be used to specify a port to connect to the Eclimd Server. Allow, Emacs Eclim to be able to specify / use these parameters.

This issue arose after @kminh reported #60.

**Comment by kminh** [comment]
Thank you for your consideration!

**Comment by nloyola** [comment]
Hi @kminh I've added the following customize settings: `eclim-eclimrc` and `eclim-nailgun-port`. You can set `eclim-eclimrc` to `~/.eclimrc` or set `eclim-nailgun-port` to `9092` for example. The Emacs Eclim package will then append these options when invoking the Eclim executable.

This implementation only supports a single workspace per Emacs session however. To use more than one workspace, you'll have to have run two diffrent instances of Emacs.

More work is required to support multiple workspaces within a single Emacs session. This will have to be added in the future.

**Comment by nloyola** [comment]
Added issue #62 to track work to support multiple workspaces.
