### ISSUE TITLE
Getting an error when visiting a java file which is in a project

### ISSUE THREAD

**Issue by parhamdoustdar** [emacs-eclim/emacs-eclim#63]
## Expected behavior

Emacs and `eclim` should work with autocompletion

## Actual behavior

When I try and use `company` with `eclim`, any sort of autocomplete freezes Emacs.

## Steps to reproduce the problem

It's as simple as opening a file in an existing project, then typing three characters to trigger autocompletion.

### package version information

Eclim version 20170522.1354.

### Java Development Kit Version

1.8.0_112

### Eclipse version

Eclipse 4.6.0 (Neon)

### Eclim version

2.6.0

### Emacs version

GNU Emacs 25.2.1 (x86_64-apple-darwin16.5.0, NS appkit-1504.82 Version 10.12.4 (Build 16E195)) of 2017-05-03

### Operating system

Mac OS 12.5

**Comment by nloyola** [comment]
Does pressing `Ctrl-g` unfreeze Emacs? If so, please attach the contents of your `*Messages*` buffer after adding this line to your Emacs Eclim config and reproducing the problem:

```emacs-lisp
(setq eclim-print-debug-messages t)
```

Did this work with previous versions of Emacs Eclim or is this the first time you try it?

I'm using almost the same versions of the software packages as you, but I run on Ubuntu 17.04 and have never encountered this error. The more information you can attach to this bug report the better.

**Comment by parhamdoustdar** [comment]
Hi,

The problem was that there was a problem with the `pom.xml` file, and this meant there was an error in the project. Solving the problem solved the issue.

Thanks for telling me more about how to debug this. Next time, my issues will have more information. :-)
