### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by nloyola** [emacs-eclim/emacs-eclim#7]
There are a lot of compiler warnings when the package is built. These should be fixed.

**Comment by nloyola** [comment]
I am currently working on this: https://github.com/nloyola/emacs-eclim/tree/compiler-warnings.

**Comment by gopar** [comment]
Once you're done, can you push the PR here so that some of us can see whats happened before merging with master? Thanks :)

**Comment by nloyola** [comment]
Will do. First I have to test the changes though.

**Comment by nloyola** [comment]
Please have a look at #9 and let me know if the changes are OK to merge into master.

There are still some compiler warnings in code that I was not able to test, and therefore did not commit the changes in these files. The files are:

* eclim-completion.el
* eclim-debug.el

**Comment by nloyola** [comment]
Fixed with #9.
