### ISSUE TITLE
"Symbol's value as variable is void" error after installing from MELPA

### ISSUE THREAD

**Issue by asenac** [emacs-eclim/emacs-eclim#7]
Consider the following basic configuration using `use-package`:

```
(use-package eclim
  :config
  (progn
    (global-eclim-mode)))
```

That downloads and compiles this plugin from this repository. After that, I always get an error like the one in the title when I try to open a java file. In fact, I need to try to open the file twice in order for it to get actually open. Once the file is open, none of the features of this plugin actually work.

However, if I go to the directory where the plugin was download, remove all compiled files (`rm -f *.elc`) and restart emacs everything works nicely as expected.

Has anyone experienced this issue before?

Thanks

**Comment by asenac** [comment]
The workaround I'm currently using to get around this issue is to download this plugin manually so it does not get compiled.

```
(add-to-list 'load-path "~/local/emacs-eclim")
(use-package eclim
  :ensure nil
  :config
  (progn
    (global-eclim-mode)))
```

**Comment by nloyola** [comment]
What version of Emacs are you using? Which OS?

**Comment by asenac** [comment]
Oop, sorry. I'm using version 24.5 in Mac OS X.

BTW, I've tried compiling the directory where I downloaded the plugin manually with `byte-recompile-directory` and everything still works as expected. I wonder why I'm getting that error when the plugin is downloaded and compiled by the `package.el` package manager.

**Comment by nloyola** [comment]
I get it to happen after using `byte-recompile-directory`. But I'm using Emacs 25.1.1 on Ubuntu. 

This is the error I get when I invoke `eclim-problems`:

```
eclim--problems-mode-init: Symbol’s value as variable is void: G0
```

I'll keep looking into it.

**Comment by emmanueltouzery** [comment]
not sure if it's related... after upgrading spacemacs, I'm getting this error when opening a java file:

```
Company backend ’company-emacs-eclim’ could not be initialized:
Symbol’s function definition is void: company-emacs-eclim
eclim--problems-mode-init: Symbol’s value as variable is void: G374
```

Is it the same issue?

**Comment by nloyola** [comment]
Does the error go away when you delete the `*.elc` files? It may be the same issue.

Do you have `company-emacs-eclim` installed?

**Comment by emmanueltouzery** [comment]
in spacemacs, best I can tell, all the `.elc` are in `~/.emacs.d/elpa`. Wiping that folder causes re-downloading packages from the package repo server and recompiling. Even after doing that, the issue persists on my machine.
I may not have company-emacs-eclim installed. spacemacs should make it happen, but....
I do see company-eclim...

**Comment by emmanueltouzery** [comment]
manually installed `company-emacs-eclim`, then loaded the java file, still the G374 error:

```
Contacting host: melpa.org:443
Making version-control local to company-emacs-eclim-autoloads.el while let-bound!
Generating autoloads for company-emacs-eclim.el...done
Wrote /home/emmanuel/.emacs.d/elpa/company-emacs-eclim-20160813.1754/company-emacs-eclim-autoloads.el
Checking /home/emmanuel/.emacs.d/elpa/company-emacs-eclim-20160813.1754... [3 times]
Compiling /home/emmanuel/.emacs.d/elpa/company-emacs-eclim-20160813.1754/company-emacs-eclim.el...done
Wrote /home/emmanuel/.emacs.d/elpa/company-emacs-eclim-20160813.1754/company-emacs-eclim.elc
Checking /home/emmanuel/.emacs.d/elpa/company-emacs-eclim-20160813.1754...
Done (Total of 1 file compiled, 2 skipped)
Package menu: Operation finished [Installed 1]
ReportingService.java has auto save data; consider M-x recover-this-file
eclim--problems-mode-init: Symbol’s value as variable is void: G374
```

**Comment by asenac** [comment]
That's the same error that I'm getting:

```
eclim--problems-mode-init: Symbol's value as variable is void: G28805
```

**Comment by nloyola** [comment]
After looking at this today, there is a problem with how the code is structured in this package. For example, functions in `eclim-problems.el` require functions defined in `elcim.el`. But `eclim.el` has a `(require 'eclim-problems)` at the end. Compiling `eclim-problems.el` fails because these functions are not defined at compile time.

It appears that the common code, used throughout the files needs to be placed in a new file, and then  `require` this new file by the files that need the common code.

For now, I would suggest to use the workaround of removing `*.elc` files until this problem is fixed.

**Comment by nloyola** [comment]
If anyone wants to try it out, I'm tyring out a fix in my forked branch here:

https://github.com/nloyola/emacs-eclim/tree/common-code

**Comment by nloyola** [comment]
I tested this on a different computer and the problems are no longer present.

**Comment by asenac** [comment]
I can confirm that the problems are no longer present in my environment either after this fix.

**Comment by asenac** [comment]
BTW, thanks a lot :)
