### ISSUE TITLE
Integrate eclipse-manage-project with projectile

### ISSUE THREAD

**Issue by schvabodka-man** [emacs-eclim/emacs-eclim#76]
Hello. Are there any work done in integration of eclipse projects and projectile?

**Comment by nloyola** [comment]
Hi @schvabodka-man, as far as I know this functionality is not there. But, is it really necessary? Most eclipse projects should already be under version control (e.g. Git) and Projectile already works with most version control systems.

**Comment by nloyola** [comment]
Closing due to no response.
