### ISSUE TITLE
start-eclimd unrecognized option: -command

### ISSUE THREAD

**Issue by Sunhick** [emacs-eclim/emacs-eclim#79]
error in process filter: /usr/bin/java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
JAVA_VERSION=8

/usr/bin/java -d64 -command project_list -Dosgi.requiredJavaVersion=1.8 -Dosgi.instance.area.default=@user.home/eclipse-workspace -XX:+UseG1GC -XstartOnFirstThread -Dorg.eclipse.swt.internal.carbon.smallFonts -Xms256m -Xmx1024m -Declipse.p2.max.threads=10 -XstartOnFirstThread -jar /Users/Sunny/eclipse/java-oxygen/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
Unrecognized option: -command
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

## Steps to reproduce the problem
- Install [Emacs 25.3](https://emacsformacosx.com/)
- Install [Eclipse 4.7.2](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/oxygen/R2/eclipse-inst-mac64.tar.gz)
- Install [eclim 2.7.1](http://eclim.org/install.html)

- configure emacs (~/.emacs.d/init.el)
```sh
(require 'eclim)
(setq eclim-eclipse-dirs "/Users/Sunny/eclipse/java-oxygen/Eclipse.app/Contents/Eclipse")
(setq eclim-executable "/Users/Sunny/eclipse/java-oxygen/Eclipse.app/Contents/Eclipse/eclimd")
(setq eclimd-autostart t)

(defun my-java-mode-hook ()
    (eclim-mode t))
(add-hook 'java-mode-hook 'my-java-mode-hook)
```

### Related issues
* https://github.com/syl20bnr/spacemacs/issues/5579 : I don't have ```eclim``` in ```/Users/Sunny/eclipse/java-oxygen/Eclipse.app/Contents/Eclipse/```. But  i have eclimd. Setting eclim-executable to ```/Users/Sunny/eclipse/java-oxygen/Eclipse.app/Contents/Eclipse/eclim``` will throw error ```wrong type argument stringp nil``` when i invoke ```start-eclimd``` from Emacs.

* https://github.com/senny/emacs-eclim/issues/137

## Environment & Version information
- Mac OS (high sierra)

### package version information
MELPA eclim              20171113.1754 installed             An interface to the Eclipse IDE.

### Java Development Kit Version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
JAVA_VERSION=8

### Eclipse version
Eclipse 4.7.2 (Oxygen)

### Eclim version
eclim 2.7.1

### Emacs version
25.3

### Operating system
Mac OS (High Sierra)

**Comment by bk322** [comment]
Same here. Why was this closed?

**Comment by casch-at** [comment]
https://github.com/emacs-eclim/emacs-eclim/wiki/Troubleshooting @bk322

**Comment by dscole** [comment]
I had the same issue and after digging around I found out that eclipse seems has multiple locations to where it installs plugins. For example I have the eclipse directory that contains plugin, a ~/.eclipse directory that seems to have plugins and a ~/.p2 directory that seems to have more. 
eclim seems to install itself in `~/.p2/pool/plugins/org.eclim_<version>`. 
you need to set `eclim-executable` to `~/.p2/pool/plugins/org.eclim_<version>/bin/eclim`. Note that it's `eclim` not `eclimd`. 
 
Now just to make it a bit more confusing eclim also installs an executable (or rather a link to an executable) called `eclimd` in the eclipse directory. It seems you should ignore that file :)

**Comment by xenomorph1096** [comment]
Dude, you are such a lifesaver .... I just could not get this to work .... good thing I found this thread ....
The instructions in the readme are not clear enough.
Since I used my OS repo to install eclipse, my eclipse root dir is /usr/lib/eclipse, but the eclim installer created a local ~/.eclipse directory... even though I specified the correct path during installation.

**Comment by alienbogart** [comment]
``

> I had the same issue and after digging around I found out that eclipse seems has multiple locations to where it installs plugins. For example I have the eclipse directory that contains plugin, a ~/.eclipse directory that seems to have plugins and a ~/.p2 directory that seems to have more.
> eclim seems to install itself in `~/.p2/pool/plugins/org.eclim_<version>`.
> you need to set `eclim-executable` to `~/.p2/pool/plugins/org.eclim_<version>/bin/eclim`. Note that it's `eclim` not `eclimd`.
> 
> Now just to make it a bit more confusing eclim also installs an executable (or rather a link to an executable) called `eclimd` in the eclipse directory. It seems you should ignore that file :)

This really should be in documentation.
