### ISSUE TITLE
Make start-eclimd async

### ISSUE THREAD

**Issue by stardiviner** [emacs-eclim/emacs-eclim#8]
I found start eclimd need to use a lot of time.
I hope `start-eclimd` can be good as `cider`. It should be async.

**Comment by nloyola** [comment]
I'm not sure what you mean. With `cider` you have to start a REPL outside of Emacs, and then in Emacs enter <kbd>M-x</kbd> `cider-connect` to connect to the REPL. 

With Eclim, the same is achieved, with a single command, within Emacs: <kbd>M-x</kbd> `start-eclimd`. However, the function has to wait and ensure the Eclim server process started successfully.

Are you proposing we add a `eclim-connect` function and start the Eclim server outside Emacs?

**Comment by stardiviner** [comment]
Oh, I see. If could, I think have a function `eclim-connect` will be great. Because start eclimd is really long....

**Comment by nloyola** [comment]
If you would like to write the code to provide this functionality, we would certainly welcome your pull request.

**Comment by stardiviner** [comment]
@nloyola I tried, and searched google with async elisp process. But still can't figure out how.
I will create PR when I finished it.
It's fine. If team not going to add this feature.

**Comment by jsoo1** [comment]
I want this feature to connect to a headed eclimd.  I want to separate the starting of eclimd and the connecting to the instance.

**Comment by nloyola** [comment]
@jsoo1, why do you think that starting the Eclim server outside of Emacs is a better way to use Eclim on Emacs?

**Comment by jsoo1** [comment]
I usually use emacs alongside eclipse and in that case it would be nice to have a connection to eclimd running in eclipse.

**Comment by nloyola** [comment]
I'm not sure what functionality you are requesting. 

At the moment I can start the Eclim server in a separate terminal and still use Eclim mode in Emacs. 

Can you please provide more details?

**Comment by nloyola** [comment]
I read the previous comments above regarding a proposed `eclim-connect` function and may be the source of some confusion here. This function is not required since the `eclim` and `eclimd` executables (installed by [eclim_2.6.0.jar](http://eclim.org/install.html)) know how to communicate with each other.

If an `eclimd` server process has been started outside of Emacs, Eclim mode in Emacs will be able to communicate with it as soon as the mode is started.

**Comment by nloyola** [comment]
I also started the Eclim server from Eclipse, and Eclim mode in Emacs can communicate with the server as well.

**Comment by jsoo1** [comment]
Ah! Ok! User error! Thanks for being so responsive!

**Comment by nloyola** [comment]
Closing this issue since the Eclim server can be started outside of Emacs.
