### ISSUE TITLE
eclim-java-delete-file interferes with tramp

### ISSUE THREAD

**Issue by CyberShadow** [emacs-eclim/emacs-eclim#80]
It looks like the `eclim-java-delete-file` advice is interfering with tramp by causing another tramp invocation, which causes a hang. Here is a stack trace (parameters redacted):

```
  accept-process-output
  tramp-accept-process-output
  tramp-wait-for-regexp
  tramp-wait-for-output
  tramp-send-command
  tramp-send-command-and-check
  tramp-get-env-with-u-option
  apply
  tramp-sh-handle-process-file--magit-tramp-process-environment
  apply
  tramp-sh-handle-process-file
  apply
  tramp-sh-file-name-handler
  apply
  tramp-file-name-handler
  apply
  process-file
  shell-command-to-string
  eclim--call-process-no-parse
  apply
  eclim--call-process
  apply
  eclim--execute-command-internal
  eclim-project-name
  eclim-java-delete-file
  apply
  ad-Advice-delete-file
  apply
  delete-file
  epg-delete-output-file
  epg-decrypt-file
  epa-file-insert-file-contents
  apply
  epa-file-handler
  insert-file-contents
  auth-source-netrc-parse
  auth-source-netrc-search
  apply
  auth-source-search-backends
  auth-source-search
  tramp-read-passwd
  tramp-action-password
  tramp-process-one-action
  tramp-process-actions
  tramp-maybe-open-connection
  tramp-send-command
  tramp-send-command-and-check
  tramp-send-command-and-read
  tramp-get-remote-path
  tramp-get-remote-readlink
  tramp-sh-handle-file-truename
  apply
  tramp-sh-file-name-handler
  apply
  tramp-file-name-handler
  file-truename
  tramp-handle-file-modes
  apply
  tramp-sh-file-name-handler
  apply
  tramp-file-name-handler
  file-modes
  after-find-file
  find-file-noselect-1
  find-file-noselect
  apply
  server-visit-files
  server-execute
  server-execute-continuation
  server-process-filter
```

It seems wrong to me that emacs-eclim is unconditionally hooking `delete-file` and trying to spin up an `eclimd` instance, even when that file has absolutely nothing to do with Java or Eclim.

## Steps to reproduce the problem

Opening a file via tramp (`/sudo:root@localhost:/...`) is enough to trigger this problem for me.

### package version information

20171113.1754

### Eclim version

*The version of Eclim installed from this site: http://eclim.org/install.html*

2.7.1

### Emacs version

25.3.1

### Operating system

Arch Linux

**Comment by nloyola** [comment]
@CyberShadow do you call `(global-eclim-mode)` anywhere in your Emacs initialization?

The advice settings are only added if `eclim-mode` is enabled for the buffer.

**Comment by CyberShadow** [comment]
No, just `(setq eclimd-autostart t)`.

**Comment by nloyola** [comment]
@CyberShadow a better way is to only enable Emacs-Eclim for Java buffers, like this:

```emacs-lisp
(defun my-java-mode-hook ()
    (eclim-mode t))

(add-hook 'java-mode-hook 'my-java-mode-hook)
```

If you are using Tramp to debug java files, you can turn off eclim-mode using `M-x eclim-mode`.

**Comment by CyberShadow** [comment]
> @CyberShadow a better way is to only enable Emacs-Eclim for Java buffers, like this:

I don't understand why that matters. As I wrote above, I *did not* open a Java file when the bug happened.

Also, I configured it according to the documentation. If the documented method is wrong, then the documentation should be updated.

**Comment by nloyola** [comment]
Yes, I realize that. I will be updating the documentation to say this instead.

**Comment by nloyola** [comment]
@CyberShadow I cannot reproduce this behaviour. Can you provide more details or maybe steps on how you got to this state?

I tried using eshell to ssh to a remote machine and then edit and delete files. I tried opening files on a remote machine using tramp syntax from find-files (C-x f). I tried deleting a file from a remote dired buffer opened using tramp. I also tried opening a file using `/sudo:root@localhost:/...`.

I'm using the config given in the README.md file.

**Comment by CyberShadow** [comment]
Apologies for the delayed response; I've had to put my Java-related work on hold due to other projects taking priority. Will ping you should I encounter this again.
