### ISSUE TITLE
eclim-java-method-signature-at-point not defined

### ISSUE THREAD

**Issue by nverno** [emacs-eclim/emacs-eclim#86]
`eclim-java-method-signature-at-point` is set in `eclim-mode-map` but isn't defined anywhere.

**Comment by nloyola** [comment]
This mapping was commented out in commit 99fda18e. The `eclim-java-method-signature-at-point` function was added in a7443a27, commented out in 4e689c35, and removed in 6243b21e. However, the mapping was not removed in those commits.

The git log only states that the code was "cleaned up".
