### ISSUE TITLE
Company: backend company-emacs-eclim error "Invalid function: "-l"" with args

### ISSUE THREAD

**Issue by emmanueltouzery** [emacs-eclim/emacs-eclim#9]
I'm seeing this error. I also have the error from https://github.com/emacs-eclim/emacs-eclim/issues/7 so that may be related to that other issue, but opening another bug just in case.

```
eclim--problems-mode-init: Symbol’s value as variable is void: G374
Company: An error occurred in auto-begin
Company: backend company-emacs-eclim error "Invalid function: "-l"" with args (candidates main)
Company: An error occurred in auto-begin
Company: backend company-emacs-eclim error "Invalid function: "-l"" with args (candidates maintenanceR)
```

**Comment by nloyola** [comment]
Melpa has a new version of Eclim, version `20160901.16`. Can you try this version and see if you get the same error?

**Comment by danielwuz** [comment]
Update to version `20160901.16` fixed the problem for me. Thanks!

**Comment by timcharper** [comment]
Updating to eclim-20161019.838 worked for me, too.

**Comment by nloyola** [comment]
Closing this issue since @danielwuz  and @timcharper say the change works.

**Comment by emmanueltouzery** [comment]
I am sorry I should have confirmed: it works for me too! Good work, thank you (I could not test much earlier because it was tied to a spacemacs upgrade for me).
